name: SwitchboardExampleDSP
options:
  bundleIdPrefix: com.synervoz
targets:

  SwitchboardExampleDSPIOS:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: src/all
        excludes:
          - "CMakeLists.txt"
      - path: src/apple
    dependencies:
      - framework: libs/switchboard-sdk/ios/SwitchboardSDK.xcframework
    settings:
      PRODUCT_NAME: SwitchboardExampleDSP
      GENERATE_INFOPLIST_FILE: YES
      USER_HEADER_SEARCH_PATHS: "libs/switchboard-sdk/include"
      CLANG_CXX_LANGUAGE_STANDARD: "gnu++17"

  SwitchboardExampleDSPMacOS:
    type: framework
    platform: macOS
    deploymentTarget: "12.3"
    sources:
      - path: src/all
        excludes:
          - "CMakeLists.txt"
      - src/apple
    dependencies:
      - framework: libs/switchboard-sdk/macOS/SwitchboardSDK.xcframework
    settings:
      PRODUCT_NAME: SwitchboardExampleDSP
      GENERATE_INFOPLIST_FILE: YES
      USER_HEADER_SEARCH_PATHS: "libs/switchboard-sdk/include"
      CLANG_CXX_LANGUAGE_STANDARD: "gnu++17"

  SwitchboardExampleDSPSampleAppIOS:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [sample-app]
    dependencies:
      - target: SwitchboardExampleDSPIOS
      - framework: libs/switchboard-sdk/ios/SwitchboardSDK.xcframework
    info:
      path: sample-app/ios/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
          UISceneConfigurations: {}
        UILaunchScreen:
          UILaunchScreen: {}
    settings:
      MARKETING_VERSION: 1.0.0