name: Build

on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10.12
        run: |
          brew install pyenv
          pyenv install 3.10.12
          pyenv global 3.10.12
          echo "PYENV_ROOT=$HOME/.pyenv" >> $GITHUB_ENV
          echo "PATH=$HOME/.pyenv/bin:$HOME/.pyenv/shims:$PATH" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup
        run: |
          python -m invoke setup

      - name: Build
        run: |
          python -m invoke build-macos

      - name: Run offline binaries
        run: |
          cd out/bin
          ./SourceOfflineDemo
          ./ProcessorOfflineDemo


  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build devcontainer image
        run: |
          docker build \
            -t sb-devcontainer \
            -f .devcontainer/Dockerfile \
            .

      - name: Setup inside container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            sb-devcontainer \
            inv setup

      - name: Build inside container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            sb-devcontainer \
            inv build-linux

      - name: Run offline binaries inside container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace/out/bin \
            sb-devcontainer \
            ./SourceOfflineDemo
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace/out/bin \
            sb-devcontainer \
            ./ProcessorOfflineDemo
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace/out/bin \
            sb-devcontainer \
            ./SinkOfflineDemo